# [Choice] Ubuntu version (use jammy or bionic on local arm64/Apple Silicon): jammy, focal, bionic
ARG VARIANT="jammy"
FROM ianepreston/base-devcontainer:${VARIANT}
# Have to set it again to be included in the build
ARG VARIANT
